### ISSUE TITLE
pu.dat status value

### ISSUE THREAD

**Issue by aagm** [Marxan-source-code/marxan#14]
There is a mismatch between latest Manual section  **5.3.3.3 Planning Unit Status** Description for status possible values (0,1,2) and the real ones within the software (using the old values in the earlier version of the manual), which could lead to the wrong misconception (0,1,2,3)

**Comment by hotzevzl** [comment]
This was fixed in the latest revision of the manual (28 September 2021), which correctly lists the 0, 1, 2, 3 values used by the software

**Comment by aagm** [comment]
Already fixed in the manual
