### ISSUE TITLE
Additional fields in input files

### ISSUE THREAD

**Issue by simonlinke** [Marxan-source-code/marxan#3]
Hi, the old executables ignored extra fields in the input files. For example in my PU file, I often have an extra field with an extended PU name. This now gives me an error (see below). Would be great if that behaviour could be reinstated because

a) I find it handy for post processing
b) A lot of users would have to modify old files.

Cheers
Simon
![image](https://user-images.githubusercontent.com/79676669/109244640-c4c2ea80-782a-11eb-84c2-136aeb5b4bab.png)

**Comment by adelebai** [comment]
Hi Simon, this should be fixed with the latest 4.0.5 version - please give it a try.
